# -*- coding: utf-8 -*-
"""Music to my Engin-ears.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10jeaFmiQDV_JEOw2OLlxzxBHqEI5u2h6
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install utils

import os
import IPython.display as ipd
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as skl
import sklearn.utils, sklearn.preprocessing, sklearn.decomposition, sklearn.svm
import librosa
import librosa.display
import utils

from google.colab import drive 
drive.mount('/content/gdrive')

#Load metadata and features

tracks = pd.read_csv('/content/gdrive/My Drive/APS360/fma_metadata/tracks.csv')
genres = pd.read_csv('/content/gdrive/My Drive/APS360/fma_metadata/genres.csv')
features = pd.read_csv('/content/gdrive/My Drive/APS360/fma_metadata/features.csv')
echonest = pd.read_csv('/content/gdrive/My Drive/APS360/fma_metadata/echonest.csv')

#Confirm arrays are the right size 
np.testing.assert_array_equal(features.index,tracks.index)
assert echonest.index.isin(tracks.index).all()

#Print shapes
tracks.shape, genres.shape, features.shape, echonest.shape

#Display first 3 rows  
print(tracks[:3])

#Select small subset
small = tracks[tracks['set.1'] == 'small']
small.shape

print('{} top-level genres'.format(len(genres['top_level'].unique())))
genres.reindex(genres['top_level'].unique()).sort_values('#tracks',ascending=False)

genres.sort_values('#tracks').head(10)

